name: CI/CD Pipeline

on: 
  push: 
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -name: Checkoutcode
    uses: actions/checkout@v2

    -name: Set up Docker Buildx
    uses: docker/setup-qemu-action@v2

    -name: Ensure Docker Compose is available
    run: docker-compose version

    -name: Copy .env.example to .env
    run: cp ./project-1/.env.example ./project-1-test/.env

    -name: Run integration scripts
    run: cd project-1-test && npm run test:integration

