name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Ensure Docker Compose is available
      run: docker compose version

    - name: Copy .env.example to .env
      run: cp ./project-1/.env.example ./project-1/.env

    - name : Give Permission
      run: chmod +x ./project-1/scripts/*
    - name: Run integration script
      run: cd project-1 && npm run test:integration
